function Hd = FilterBank(Fct, Fs)
% Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 28-Feb-2021 12:56:40

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 16000;  % Sampling Frequency
% Fct: centre frequency
N = 10;   % Order
Fc1 = round(Fct / nthroot(2, 6));   % First Cutoff Frequency
Fc2 = round(nthroot(2, 3) * Fc1);   % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
end
%% Usage
% https://se.mathworks.com/help/signal/gs/exporting-filters-from-filter-designer.html